### ISSUE TITLE
Not getting messages

### ISSUE THREAD

**Issue by notsolowki** [sandeepmistry/arduino-CAN#122]
Hi, ive wired a TJA1050 to the ESP32 NodeMCU.. However when i connect the transceiver to a canbus i dont see anything in the serial monitor.  Ive tried various other examples but i cant get anything in the serial console. i have confirmed data from the transceiver to the ESP32 but nothing happens in the serial console as if no messages are received. can someone help me please.

**Comment by Nhanbee** [comment]
Have you found a solution yet?
