### ISSUE TITLE
Can't set 33.3kbps baudrate

### ISSUE THREAD

**Issue by mister0wl** [sandeepmistry/arduino-CAN#15]
Hello!
I use your library with ESP32 + SN65HVD230 transceiver. It works well on all pre-defined baudrate but I needed two special, too. I quickly managed to set up 95.238 using the calculation method in the source at https://github.com/nhatuan84/arduino-esp32-can-demo but I simply cannot manage 33.3kbps and it drives me mad. I tried Kvaser's calculator and also http://www.esacademy.com/en/library/calculators/sja1000-timing-calculator.html, no luck. I tried

```
    case (long)33E3:
      modifyRegister(REG_BTR1, 0x0f, 0x0c);
      modifyRegister(REG_BTR0, 0x3f, 75); 
```
according to Arduino-ESP32 method, and
```
    case (long)33E3:
      modifyRegister(REG_BTR1, 0x0f, 0x0c);
      modifyRegister(REG_BTR0, 0xfe, 0x8a);

```
according to Esacademy's calculator. Then I tried every single value between 62 and 124 for 
`modifyRegister(REG_BTR0, 0x3f, 62);
`
also no luck. I didn't want to ask such silly thing but I'm out of ideas. Could you please give me a clue what I did wrong?

Thank you in advance!

**Comment by mister0wl** [comment]
As my post generated a rather moderate interest, I tried hard to do my homework. I'm very grateful as I could learn a lot. :) However, this is a bad news for all of us. Since the BTR0 register only allows 6 bits for setting up BRP, it is impossible to set up frequencies below 50kbps because the ESP32 CAN bus controller (SJA1000 compatible) clock frequency is bound to the ESP32's APB clock frequency that is 80MHz. As the biggest BRP value could be only 0x3f, this renders any baudrates below "50E3" impossible.

This is a limitation of the hardware, not the library, but there's no point for 40E3, 20E3 and 10E3, in fact this is misleading as it looks like it supports CANopen however it isn't. I propose to remove those branches in the switch baudrate section in ESP32SJA1000.cpp and mention this somewhere in the code.

Pls also see https://esp32.com/viewtopic.php?t=2142

Cheers!

**Comment by sandeepmistry** [comment]
> I propose to remove those branches in the switch baudrate section in ESP32SJA1000.cpp and mention this somewhere in the code.

@mister0wl would you like to make a pull request for this suggestion?

**Comment by mister0wl** [comment]
Well... I'm still learning Github but I'll try. Thanks!

**Comment by sandeepmistry** [comment]
Closed via #17.

**Comment by ale1800** [comment]
Hi, I'm trying to do an obd reader with your same hardware (esp+sn65vh230) but I'm finding some difficulties to write right code. Im trying the examples but no one works. Could you please share yours? thanks in advance

**Comment by zalexzperez** [comment]
@mister0wl 
I'm trying to use your forked version. 
I also need to use the baudrate at 33.3kbps with a newer ESP32 devkitc V4

What are the  modifyRegister correct values? 

Thanks!
