### ISSUE TITLE
ESP32 - how can i setup another baud rate?

### ISSUE THREAD

**Issue by latonita** [sandeepmistry/arduino-CAN#2]
HI,

After atmel +mcp2515 i'm trying to use ESP32 for can bus communication.
However I can't set custom speed. I need 83.333 kbps.
How did you calculated BTR register values? tried kvasir bit calculator, but can't get same numbers. dont know clock frequency at least.
I managed to use excel :) and to interpolate required bit rate with nice formula:
 BTR0 = 2989,2 * BAUD ^ -1,05
for 83.333 i got BTR0 = 29. And it works!!!! 👍 

```
    case (long)80E3:
      modifyRegister(REG_BTR1, 0x0f, 0x0c);
      modifyRegister(REG_BTR0, 0x3f, 30);
      break;
```

**Comment by sandeepmistry** [comment]
@latonita it's based on https://github.com/nhatuan84/arduino-esp32-can-demo/blob/master/src/CAN.c#L204-L205

**Comment by latonita** [comment]
Clear, thank you! 02:46, April 30, 2018, Sandeep Mistry <notifications@github.com>:@latonita it's based on https://github.com/nhatuan84/arduino-esp32-can-demo/blob/master/src/CAN.c#L204-L205

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




-- Sent from Yandex.Mail for mobile: http://m.ya.ru/ymail
