### ISSUE TITLE
Send and receive bits

### ISSUE THREAD

**Issue by mariliahoshino** [sandeepmistry/arduino-CAN#50]
I'd like send and receiver bits of data,not character 
I will use in maintenance of machine

![20200814_193104](https://user-images.githubusercontent.com/62081861/90298432-a6863600-de68-11ea-825f-5462bb645f69.jpg)

I'd like set the bits 32 33 and 34
I need sent slot of zero and position 32 33 and 34 send 1 
I need sent this 000000000000000000000000000000 0111000000000000000000000000000000

Tks

**Comment by timurrrr** [comment]
I suggest creating a custom struct in C (e.g. bit field [1]) and sending it as bytes.
Sending individual bits via API calls is typically very inefficient.

[1] https://en.cppreference.com/w/cpp/language/bit_field
