### ISSUE TITLE
Doesn't work on SN65HVD230 Transceiver

### ISSUE THREAD

**Issue by ruffle-b** [sandeepmistry/arduino-CAN#6]
Nice library but it doesn't work on a SN65HVD230 Transceiver (which are now very common).

Using your simple EngineRPM demo; it hangs at CAN.endPacket() (the standard can library in esp-idf does work with SN65HVD230).

Weirdly, if I put a Serial.println immediately before that it not only hangs but I have to power cycle my ESP32 before it will talk again:

```
CAN.write(0x0c); // engine RPM
Serial.println("Written 0x0c");
CAN.endPacket();
```

**Comment by rahmaevao** [comment]
Hi, all.
It is problem have a solution.
Very important chip imaging.
Set the terminator to 60 ohms.
If the free standing on the bus is not 1.65 V, then use pull-up resistors for this.
CANH > RES 3kOhm > GND (Pull down)
CANL > RES 3kOhm > +3,3 V (Pull up)

**Comment by rahmaevao** [comment]
Does not work with ADM3053 in standard piping

**Comment by rahmaevao** [comment]
With braces also does not work

**Comment by rahmaevao** [comment]
Why?

**Comment by rahmaevao** [comment]
Driver ADM3053 also works.))

**Comment by quadcodes** [comment]
I tried using with my Suzuki. I'm getting following data on CAN BUS.

```
Received packet with id 0x13 and length 4

?0p

Received packet with id 0x39 and length 0


Received packet with id 0x41 and length 0


```
How do I read/parse this data as OBD response ?

**Comment by rahmaevao** [comment]
![image](https://user-images.githubusercontent.com/33318971/44265786-beeaf800-a230-11e8-8900-08285748da64.png)

Your data is output if the LENGTH is not zero.

**Comment by sandeepmistry** [comment]
@rahmaevao thanks for the tips!

**Comment by sandeepmistry** [comment]
Closing due to lack of feedback.
