### ISSUE TITLE
Possibly missing packets?

### ISSUE THREAD

**Issue by alexvnesta** [sandeepmistry/arduino-CAN#67]
I am using this library with an ESP32 and MCP2551. On my test bench, everything seems to work fine.

I am trying to detect when a steering wheel button is pressed. If I spam the button when everything is in the car, it is detected. But the message takes a while to be detected. If I just press the button regularly, it is not detected.

I'm using the example code to detect can messages, but I'm only interested in a select few. Does anyone have any suggestions on optimizing the code to detect just a handful of can IDs reliably?

Or is this a hardware issue?

Thanks,
Alex

**Comment by Petros144** [comment]
Hi alex,

I work with the Onboard can controler on the ESP, and only add a tranciver. This combination works great for me.
If you want to test out your setup with the Onboard ESP controler I can help you.
