### ISSUE TITLE
DLC=0 frames aren't received

### ISSUE THREAD

**Issue by DerMax93** [sandeepmistry/arduino-CAN#7]
I used the library for testing one of my builds and I noticed that it doesn't properly receive frames with DLC=0. While uncommon this type of frame is not ruled-out by the standard. The MCP2515 does acknowledge the frame on the bus properly, but the library does not forward it to the user-code.

I "fixed" the problem in my version by changing the return value of an empty frame to -1 (in parsePacket-function) and checking for a positive return-value in the polling-loop. Maybe you want to incorporate a similar fix into your version.

**Comment by sandeepmistry** [comment]
Closing due to lack of feedback.
