### ISSUE TITLE
No CAN communication

### ISSUE THREAD

**Issue by LK231195** [sandeepmistry/arduino-CAN#8]
Hi,
I tried to connect 2 Arduino UNO with 2 MKR CAN Shields. I uploaded the examples "CANReceiver" and "CANSender" successfully but I have no connection. The serial monitor from CANSender shows "CAN Sender, Sending packet ..." and the CANReceiver shows "CAN Receiver". 
Is the Arduino UNO not compatible with the MKR CAN Shield? Should I make any additional configurations?
Thanks!
LK231195

**Comment by sandeepmistry** [comment]
Please share more details on the wiring of your setup.
