### ISSUE TITLE
No data received with Leonardo ETH

### ISSUE THREAD

**Issue by mckraemer** [sandeepmistry/arduino-CAN#9]
Hello,

first thank you for the quick response on Twitter. I have a problem, I don't receive data with the CAN library or the OBD2 library. 
I use the Twitter shared module in combination with a Leonardo ETH. I can upload a picture of the wiring if needed.
https://imgur.com/2IWky3M
I added `CAN.setClockFrequency(8E6); CAN.setPins(10, 2);` to your Supported PID example.
Do you have an idea?

**Comment by sandeepmistry** [comment]
@mckraemer could you please share the full sketches you are using, as well as more details on the wiring for CAN to CAN testing.

**Comment by mckraemer** [comment]
@sandeepmistry That was my mistake. I used pin 10 as defined in the standard, but for the Arduino this is the CS for the Ethernet. Thanks a lot!
